---
title: C6312 |Microsoft Docs
ms.custom: ''
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.reviewer: ''
ms.suite: ''
ms.technology:
- vs-devops-test
ms.tgt_pltfrm: ''
ms.topic: article
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: c2d627c4b8387e43b154ca6f2fb1d3ae334a70bd
ms.sourcegitcommit: af428c7ccd007e668ec0dd8697c88fc5d8bca1e2
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 11/16/2018
ms.locfileid: "51816758"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

警告 C6312： 可能的無限迴圈： 常數 exception_continue_execution 一試的例外狀況篩選條件運算式中使用-除外  
  
 這則警告表示常數的使用`EXCEPTION_CONTINUE_EXECUTION`（或另一個常數，其值為-1） 的結構化例外狀況處理常式的篩選條件運算式中。 使用常數值的`EXCEPTION_CONTINUE_EXECUTION`可能會導致無限迴圈。 比方說，如果硬體所引發的例外狀況，則會重新啟動造成例外狀況的指示。 如果仍然不正確所造成的例外狀況的位址，另一個例外狀況會發生，而且相同的方式來處理。 這會導致無限迴圈。  
  
 明確呼叫`RaiseException`不是直接將造成無限迴圈，但是它會繼續執行程式碼中的受保護的區塊。 這可以是預期的情況，而且可能會導致無限迴圈如果`RaiseException`用來避免取值無效指標。  
  
 一般而言，`EXCEPTION_CONTINUE_EXECUTION`應只由呼叫在篩選運算式中，有機會修正造成例外狀況的指標，或是基礎記憶體的函式傳回。  
  
## <a name="example"></a>範例  
 下列程式碼會產生這個警告：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 若要更正這個警告，請使用下列程式碼：  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```



