---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 683619442865a231742fdecba9e94a893d103144
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 02/15/2020
ms.locfileid: "77267028"
---
# <a name="c6318"></a>C6318
警告 C6318：定義錯誤的 __try/\__except：在例外狀況篩選條件運算式中使用常數 EXCEPTION_CONTINUE_SEARCH 或判斷值為零的另一個常數。 未執行例外狀況處理常式區塊中的程式碼

 此警告表示，如果此結構化例外狀況處理常式的受保護區塊中發生例外狀況，將不會處理例外狀況，因為在例外狀況篩選條件運算式中使用常數 `EXCECPTION_CONTINUE_SEARCH`。

 此程式碼相當於不含例外狀況處理常式區塊的 protected 區塊，因為不會執行處理常式區塊。

## <a name="example"></a>範例
 下列程式碼會產生這個警告：

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 若要修正這個警告，請使用下列程式碼：

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>另請參閱
 [try-except 陳述式](/cpp/cpp/try-except-statement)
