---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: bd2cc95cf0dd14f4ee429cf542a54fcb53947ea4
ms.sourcegitcommit: 5f6ad1cefbcd3d531ce587ad30e684684f4c4d44
ms.translationtype: MT
ms.contentlocale: zh-TW
ms.lasthandoff: 10/22/2019
ms.locfileid: "72746328"
---
# <a name="c6320"></a>C6320
警告 C6320：例外狀況-篩選條件運算式是常數 EXCEPTION_EXECUTE_HANDLER。 這可能會遮罩不打算處理的例外狀況

 此警告表示在 __except 區塊中使用 EXCEPTION_EXECUTE_HANDLER 常數的副作用。 在此情況下，\__except 區塊中的語句一律會執行來處理例外狀況，包括您不想要在特定函數中處理的例外狀況。 建議您先檢查例外狀況，然後再進行處理。

## <a name="example"></a>範例
 下列程式碼會產生此警告，因為 __except 區塊會嘗試處理所有類型的例外狀況：

```
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

 若要修正這個警告，請使用 `GetExceptionCode` 來檢查特定的例外狀況，然後進行處理，如下列程式碼所示：

```
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>請參閱
 [try-except 陳述式](/cpp/cpp/try-except-statement)
